name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deploy script
        run: /home/mcc/mcc_website/deploy.sh
        shell: bash